upstream flask_backend{
    server app:5000;
}

server {
    listen 80;
    server_name localhost;
    client_max_body_size 6M;


    location /static/ {
        alias /static/;
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }

    location / {
        proxy_pass http://flask_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
